# .github/workflows/netlify.yml
name: Build and Deploy to Netlify
on:
  release:
    types: [published]
    branches: main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: netlify-deploy
      url: https://taskorial.netlify.app/
    steps:
      - uses: actions/checkout@v3
      - name: "deployed site"
        run: curl -X POST -d {} ${{ secrets.NETLIFY_BUILD_HOOK }}
      
