on:
  release:
    types: [published]
    branches: main

jobs:
  ci:
    runs-on: ubuntu-latest
    environment:
      name: render-deploy
      url: https://to-do-list-server-lqa9.onrender.com
    steps:
      - uses: actions/checkout@v3
      - name: install and run
        run: |
          cd server
          npm install

      - name: Deploy
        # Only run this step if the branch is main
        if: github.ref == 'refs/heads/main'
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          curl "$deploy_url"
