name: Build and Deploy to Render
on:
  release:
    types: [published]
    branches: main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: render-deploy
      url: https://to-do-list-server-lqa9.onrender.com
    steps:
      - uses: actions/checkout@v3
      - name: "deployed site"
        run: curl -X POST -d {} ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
